### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by balrog69-420** [hack-mans/Unity-ControlNet-Rig#3]
hey hackman, i installed unity and such. when running the thing im not sure its connecting to the webui.bat when clicking generate it just gives an error. 
![image](https://user-images.githubusercontent.com/122206427/233843848-06f8c975-a41b-4686-88c0-8fb258a15a79.png)

**Comment by balrog69-420** [comment]
hmm, i relaunched unity and i think the key was to list models again and make sure a model was selected on the right side in "openposecontroller" perhaps add that to the guide. having never used unity before it took me an hour to figure out how to get it working initialy.

**Comment by hack-mans** [comment]
@balrog69-420 Thank you for mentioning, I'll make this clearer in my instructions.
